/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rps_kotlin

import rps_kotlin.Hand.*
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun testRoundResults() {
        assertEquals(roundResult(SCISSORS, ROCK), RoundResult.LOSS)
        assertEquals(roundResult(ROCK, ROCK), RoundResult.DRAW)
        assertEquals(roundResult(PAPER, ROCK), RoundResult.WIN)

        assertEquals(roundResult(SPOCK, ROCK), RoundResult.WIN)
        assertEquals(roundResult(SPOCK, SCISSORS), RoundResult.WIN)
        assertEquals(roundResult(SPOCK, LIZARD), RoundResult.LOSS)
        assertEquals(roundResult(SPOCK, PAPER), RoundResult.LOSS)
        assertEquals(roundResult(SPOCK, SPOCK), RoundResult.DRAW)

        assertEquals(roundResult(LIZARD, ROCK), RoundResult.LOSS)
        assertEquals(roundResult(LIZARD, SCISSORS), RoundResult.LOSS)
        assertEquals(roundResult(LIZARD, LIZARD), RoundResult.DRAW)
        assertEquals(roundResult(LIZARD, SPOCK), RoundResult.WIN)
        assertEquals(roundResult(LIZARD, PAPER), RoundResult.WIN)
    }

    @Test
    fun testPlayRoundsSimpleStrategyDraws() {
        val numberOfRounds = 10
        val results = playRounds(numberOfRounds, ::chooseRock, ::chooseRock)
        assertEquals(results.draws, numberOfRounds)
        assertEquals(results.wins, 0);
        assertEquals(results.losses, 0);
    }

    @Test
    fun testPlayRoundsSimpleStrategyWins() {
        val paperStrat = { PAPER }
        val numberOfRounds = 10
        val results = playRounds(numberOfRounds, paperStrat, ::chooseRock)
        assertEquals(results.wins, numberOfRounds)
        assertEquals(results.draws, 0);
        assertEquals(results.losses, 0);
    }

    @Test
    fun testPlayRoundsSimpleStrategyLosses() {
        val scissorStrategy = { SCISSORS }
        val numberOfRounds = 10
        val results = playRounds(numberOfRounds, scissorStrategy, ::chooseRock)
        assertEquals(results.losses, numberOfRounds)
        assertEquals(results.wins, 0);
        assertEquals(results.draws, 0);
    }
}
