/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rps_kotlin

import rps_kotlin.Result
import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testRockBeats() {
        assertEquals(beats(Hand.ROCK, Hand.ROCK), false)
        assertEquals(beats(Hand.ROCK, Hand.PAPER), false)
        assertEquals(beats(Hand.ROCK, Hand.SCISSORS), true)
    }

    @Test fun testPaperBeats() {
        assertEquals(beats(Hand.PAPER, Hand.ROCK), true)
        assertEquals(beats(Hand.PAPER, Hand.PAPER), false)
        assertEquals(beats(Hand.PAPER, Hand.SCISSORS), false)
    }

    @Test fun testScissorsBeats() {
        assertEquals(beats(Hand.SCISSORS, Hand.ROCK), false)
        assertEquals(beats(Hand.SCISSORS, Hand.PAPER), true)
        assertEquals(beats(Hand.SCISSORS, Hand.SCISSORS), false)
    }

    @Test fun testRoundResults() {
        assertEquals(roundResult(Hand.SCISSORS, Hand.ROCK), Result.LOSS)
        assertEquals(roundResult(Hand.ROCK, Hand.ROCK), Result.DRAW)
        assertEquals(roundResult(Hand.PAPER, Hand.ROCK), Result.WIN)
    }

}
