/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package rps_kotlin

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun rockStratChoosesRock() {
        assertEquals(chooseRock(), Hand.ROCK)
    }
}
